### ISSUE TITLE
it's not work

### ISSUE THREAD

**Issue by simongaocd** [oracle-quickstart/oci-arch-tomcat-mds#1]
no tomcat and app installed.  network security list did't config.

**Comment by oegentil** [comment]
Tomcat is indeed not being installed. Still working in the automation.
I'll double-check the security list.
Thanks for the feedback.

**Comment by oegentil** [comment]
@simongaocd 
the network security lists/SNGs are correct and working.
As the server config is not included yet, iptables is not adjusted.
In the meantime, if you want to manually configure it:
$ sudo firewall-cmd --add-port=8080/tcp --permanent
$ sudo firewall-cmd --reload

**Comment by lfeldman** [comment]
The issue seems to be fixed.
